name: Continuous Integration and Pull Requests

on:
  push:
    branches:
      - "*"
      - "!master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    name: Push to master
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Check go version
        run: go version

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: "--tests=false"

      - name: Tests
        run: make test